FROM golang:1.24.1-alpine3.21 AS build

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /out/tflive-worker ./cmd/worker

FROM alpine:3.21

ARG OPENTOFU_VERSION=1.12.5
ARG TARGETARCH

RUN apk add --no-cache ca-certificates git \
    && wget -qO /tmp/tofu.tar.gz \
        "https://github.com/opentofu/opentofu/releases/download/v${OPENTOFU_VERSION}/tofu_${OPENTOFU_VERSION}_linux_${TARGETARCH}.tar.gz" \
    && tar -xzf /tmp/tofu.tar.gz -C /usr/local/bin tofu \
    && rm /tmp/tofu.tar.gz \
    && addgroup -S tflive \
    && adduser -S -D -H -G tflive tflive
COPY --from=build /out/tflive-worker /usr/local/bin/tflive-worker

USER tflive
ENTRYPOINT ["/usr/local/bin/tflive-worker"]
